version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run:
            name: Which bundler?
            command: bundle -v
        - ruby/bundle-install
        - run:
            name: Sonar Scan
            command:
        - sonarcloud/scan

        workflows:
          main:
            jobs:
              - build:
                  context: SonarCloud